version: '3'
services:

  ### nginx Container ############################################
  nginx:
    image: nginx
    volumes:
      - ./app/www/:/var/www/
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
    container_name: nginx
    ports:
      - 8081:80
    networks:
      - backend

  ### php Container ############################################
  php7:
    image: lawxen/drupal:7-fpm
    volumes:
      - ./app/www/:/var/www/
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    container_name: php
    expose:
      - "9000"
    networks:
      - backend

    ### php Container ############################################
  php8:
    image: lawxen/drupal:8-fpm
    volumes:
      - ./app/www/:/var/www/
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    container_name: php
    expose:
      - "9000"
    networks:
      - backend

  ### Redis Container #########################################
  redis:
    image: bitnami/redis:4.0-debian-9
    container_name: redis
    environment:
      - REDIS_PASSWORD=c4200bc580
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - 6379:6379
    networks:
      - backend

  ### Mariadb Container #######################################
  mariadb:
    image: mariadb:10.4
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./etc/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
    container_name: mariadb
    restart: always
    networks:
      - backend

### Network ###############################################
networks:
  backend:
    driver: "bridge"
