version: "3"
services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./app/web:/var/www

  php7-fpm-d8:
    image: helloxiaoxin/php7-version:d8-memcache-redis
    expose:
      - "9000"
    volumes:
      - ./app/web:/var/www
      - ./etc/php:/usr/local/etc

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./etc/mariadb/conf.d:/etc/mysql/conf.d
      - ./etc/mariadb/my.cnf:/etc/mysql/my.cnf
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"

  memcached:
    image: memcached

  redis:
    image: redis